function cylinderbetweenpoints(R, N,r1,r2,facecolo,edgecolo)
[x0, y0, z0] = cylindertwopoints(R, N,r1,r2);
surf(x0,y0,z0,'FaceColor',facecolo,'Facealpha',0.6, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
patch('Vertices',[x0(1,:)' y0(1,:)' z0(1,:)'], ...
'Faces',[1:10],'FaceColor',facecolo, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
patch('Vertices',[x0(2,:)' y0(2,:)' z0(2,:)'], ...
'Faces',[1:10],'FaceColor',facecolo, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)

end